
import './index.scss'
import './styles/slider/slider'
import './styles/card/card'

import './images/slide_1_bg_light.png'
import './images/slide_2_bg.png'
import './images/slide_3_bg.png'
import './images/card_1_bg.png'
import './images/card_2_bg.png'
import './images/card_5_bg.png'
import './images/card_7_bg.png'
import './images/card_3_bg_m.png'
import './images/card_6_bg_m.png'
import './images/card_4_bg_r.png'
import './images/card_1_bg_lg.png'
import './images/card_2_bg_lg.png'
import './images/card_3_bg_lg.png'
import './images/icons/marker_point.svg'
import './images/icons/location_orange_icon.svg'
import './images/icons/events_orange_icon.svg'

